config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'

  get 'home/index'

  devise_for :users
  
  root 'home#index'
  
  resources :contacts, except: :show do
    get 'autocomplete', on: :collection
  end

  post 'groups', to: 'groups#create'
  get '/dashboard', to: 'dashboard#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  belongs_to :group
  belongs_to :user

  validates :name, :email, :group_id, presence: true
  validates :name, length: { minimum: 2 }

  def gravatar
    size = "?s=200"
    default = "?d=robohash"
    hash = Digest::MD5.hexdigest(email.downcase)
    "https://www.gravatar.com/avatar/#{hash}#{size}#{default}"
  end

  scope :search, -> (term) { where('LOWER(name) LIKE :find OR LOWER(company) LIKE :find OR LOWER(email) LIKE :find OR LOWER(address) LIKE :find OR LOWER(phone) LIKE :find', find: "%#{term.downcase}%") if term.present? }

  scope :by_group, -> (group_id) { where(group_id: group_id) if group_id.present? }

end

app/models/group.rb
class Group < ApplicationRecord
  has_many :contacts
  belongs_to :user

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, 
        :trackable, :validatable
  validates :name, presence: true
  has_many :contacts
  has_many :groups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    registration_params = [:name, :email, :password, :password_confirmation]

      if params[:action] == 'update'
        devise_parameter_sanitizer.permit(:account_update) do |u| 
          u.permit(registration_params << :current_password)
        end
      elsif params[:action] == 'create'
        devise_parameter_sanitizer.permit(:sign_up) do |u| 
          u.permit(registration_params) 
        end
      end
  end

  def after_sign_in_path_for(resource)
    dashboard_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :find_contact, only: [:edit, :update, :destroy]

  def index
    session[:selected_group_id] = params[:group_id]
    @contacts = current_user.contacts.by_group(params[:group_id]).search(params[:term]).order(created_at: :desc).page(params[:page]).per(5)
  end

  def autocomplete
    @contacts = current_user.contacts.search(params[:term]).order(created_at: :desc).page(params[:page])
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = current_user.contacts.build(contact_params)
    respond_to do |format|
      if @contact.save
        format.html do
          flash[:success] = 'Contact was successfully created.'
          redirect_to contacts_path(previous_query_string)
        end
      else
        format.html do
          flash[:error] = 'Contact failed to be created.'
          render 'new'
        end
      end
    end
  end

  def edit
    authorize @contact
  end

  def update
    authorize @contact
    respond_to do |format|
      if @contact.update(contact_params)
        format.html do
          flash[:success] = 'Contact has been updated successfully.'
          redirect_to contacts_path(previous_query_string)
        end
      else
        format.html do
          flash[:error] = 'Contact failed to be updated.'
          render 'edit'
        end
      end
    end
  end

  def destroy
    @contact.destroy
    respond_to do |format|
      format.html do
        flash[:success] = 'Contact has been deleted.'
        redirect_to contacts_path(previous_query_string)
      end
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :company, :address, :phone, :group_id, :avatar)
  end

  def find_contact
    @contact = Contact.find(params[:id])
  end

  def previous_query_string
    session[:selected_group_id] ? { group_id: session[:selected_group_id] } : {}
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def create
    @group = current_user.groups.build(group_params)
    if @group.save
      render json: @group, status: :created
    else
      render json: @group.errors.full_messages, status: :unprocessable_entity
    end
  end

  private

  def group_params
    params.require(:group).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def conversion_alert(type)
    case type
    when "notice"
      type = "primary"
    when "error"
      type = "danger"
    when "success"
      type = "success"
    when "alert"
      type = "info"
    else
      type = "dark"
    end
  end

  def active?(path)
    "active" if current_page?(path)
  end

  def nav_link(path)
    if current_user.present?
      dashboard_path
    else
      root_path
    end
  end

  def has_error?(resource, attribute)
    'is-invalid' if resource.errors.messages[attribute].present?
  end

  def get_error(resource, attribute)
    resource.errors.messages[attribute].join(', ')
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper

  def contact_image(contact)
    @contact = contact
    if @contact.avatar.present?
      @contact.avatar.url(:avatar)
    elsif @contact.email.present? 
      @contact.gravatar
    else
      "https://imgplaceholder.com/200x200?text=No+Image&font-family=OpenSans_Bold_Italic"
    end
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/_badges.html.erb
<% active = (params[:group_id] == nil || params[:group_id].empty?) && !session[:selected_group_id] ? 'active' : '' %>
<%= link_to contacts_path, class: "list-group-item #{active}", remote: true do %>
  All Contacts
  <span class="badge badge-secondary badge-pill">
    <%= current_user.contacts.count %>
  </span>
<% end %>

<% current_user.groups.each do |group| %>
  <% active = params[:group_id].to_i == group.id || (session[:selected_group_id] && session[:selected_group_id].to_i == group.id) ? 'active' : '' %>
  <%= link_to contacts_path(group_id: group.id), class: "list-group-item #{active}", remote: true do %>
    <%= group.name.capitalize %>
    <span class="badge badge-secondary badge-pill">
      <%= group.contacts.count %>
    </span>
  <% end %>
<% end %>

app/views/contacts/_contact.html.erb
<div class="card card-custom bg-white border-white border-0 contact-card-container">
  <div class="row no-gutters contact-elements">
    <div class="col-auto">
      <%= image_tag contact.avatar.present? ? contact.avatar.url(:avatar) : contact.gravatar, class: "img-fluid gravatar-img" %>
    </div>
    <div class="col contact-description">
      <div class="card-block px-2">
        <h4 class="card-title">
          <%= contact.name %>
        </h4>
        <p class="card-text">
          <strong><%= contact.company %></strong><br>
          <%= contact.email %><br>
          <%= contact.address if contact.address.present? %><br>
          <%= contact.phone if contact.address.present? %><br>
          
        </p>
      </div>
    </div>
    <div class="col contact-actions">
      <%= link_to '', edit_contact_path(contact), class: "text-secondary glyphicon glyphicon-pencil contact-action-icon", title: "Edit", data: {toggle: "modal", target: "#form-modal"}, remote: true %>
      <%= link_to '', contact_path(contact), method: :delete, class: "text-danger glyphicon glyphicon-trash contact-action-icon", title: "Delete", data: { confirm: "Are you sure?" }, remote: true %>
    </div>
  </div>
</div>

app/views/contacts/_contacts.html.erb
<% if @contacts.blank? %>
  <div class="alert alert-warning">
    <strong>Contact not found!</strong> Add some contacts please.
  </div>
<% end %>

<div id="contacts">
  <%= render @contacts %>
</div>

<br>

<div class="text-center">
  <div class="pagination pagination-lg justify-content-center" id="paginator">
    <%= paginate @contacts, remote: true %>
  </div>
</div>

<!-- Modal new contact -->
<div class="modal fade" id="form-modal" tabindex="-1" role="dialog" aria-labelledby="form-modal"
  aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="form-modal-title"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="form-modal-body" id="form-modal-body">
      </div>
      <div class="card-footer">
        <button type="button" class="btn btn-primary" id="form-modal-save-btn">Save changes</button>
        <button type="button" class="btn btn-outline-primary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/contacts/_form.html.erb
<%= form_for(@contact, html: { multipart: true }, remote: local_assigns[:hide_buttons], authenticity_token: true) do |f| %>
  <div class="card-body">
    
    <div class="card-text">
      <div class="row">
        <div class="col-md-8">

          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control #{has_error?(@contact, :name)}" %>
            <% if #{has_error?(@contact, :name)} %>
              <div class="invalid-feedback">
                <%= get_error(@contact, :name) %>
              </div>
            <% end %>
          </div>

          <div class="form-group">
            <%= f.label :company %>
            <%= f.text_field :company, class: "form-control #{has_error?(@contact, :company)}" %>
            <% if #{has_error?(@contact, :company)} %>
              <div class="invalid-feedback">
                <%= get_error(@contact, :company) %>
              </div>
            <% end %>
          </div>

          <div class="form-group">
            <%= f.label :email %>
            <%= f.text_field :email, class: "form-control #{has_error?(@contact, :email)}" %>
            <% if #{has_error?(@contact, :email)} %>
              <div class="invalid-feedback">
                <%= get_error(@contact, :email) %>
              </div>
            <% end %>
          </div>

          <div class="form-group">
            <%= f.label :phone %>
            <%= f.text_field :phone, class: "form-control #{has_error?(@contact, :phone)}" %>
            <% if #{has_error?(@contact, :phone)} %>
              <div class="invalid-feedback">
                <%= get_error(@contact, :phone) %>
              </div>
            <% end %>
          </div>

          <div class="form-group">
            <%= f.label :address %>
            <%= f.text_area :address, class: "form-control #{has_error?(@contact, :address)}", rows: 3 %>
            <% if #{has_error?(@contact, :address)} %>
              <div class="invalid-feedback">
                <%= get_error(@contact, :address) %>
              </div>
            <% end %>
          </div>

          <div class="form-group">
            <%= f.label :group %>
            <% attr = { prompt: "Select Group"} %>
            <% attr[:selected] = session[:selected_group_id].to_i if session[:selected_group_id] %>
            <%= f.collection_select :group_id, current_user.groups, :id, :name, attr, class: "form-control #{has_error?(@contact, :group)}" %>
            <% if #{has_error?(@contact, :group)} %>
              <div class="invalid-feedback">
                <%= get_error(@contact, :group) %>
              </div>
            <% end %>
            <br>

            <!-- Group Input -->
            <div class="input-group mb-2 new_group" id="add-new-group">
              <div class="input-group-prepend">
                <a id="save-group-btn" class="input-group-text btn btn-success">
                  <i class="glyphicon glyphicon-ok"></i>
                </a>
              </div>


              <input type="text" name="new_group" id="new_group" id="new_group" class="form-control" placeholder="My new group">


            </div>

            <br>
            <a href="#" id="add-group-btn" class="btn btn-outline-primary btn-block">Add New Group</a>
            <!-- End Group Input -->

          </div>

        </div>
        <div class="col-md-4">
          <div class="contact-avatar-container fileinput fileinput-new" data-provides="fileinput">
            <%= image_tag contact_image(@contact), class: "img-fluid gravatar-img contact-avatar card-custom", data: { trigger: "fileinput" } %>
            <br>

            <div class="text-center">
              <span class="btn btn-secondary btn-file"><span class="fileinput-new">Select image</span><span class="fileinput-exists">Change</span><%= f.file_field :avatar %></span>
              <a href="#" class="btn btn-secondary fileinput-exists" data-dismiss="fileinput">Remove</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <% unless local_assigns[:hide_buttons] %>
    <div class="card-footer">
      <%= f.submit @contact.new_record? ? "Save" : "Update", class: "btn btn-primary" %>
      <%= link_to "Cancel", root_path, class: "btn btn-outline-primary" %>
    </div>
  <% end %>

<% end %>

app/views/contacts/edit.html.erb
<div class="col-md-12">
  <div class="card bg-default card-custom border-white border-0 contact-card-container">
    <h5 class="card-header">
      Edit Contact
    </h5>
  
    <%= render 'form' %>
  </div>
</div>

app/views/contacts/edit.js.erb
$('#form-modal-title').html('Edit Contact')
$('#form-modal-body').html('<%= j render("contacts/form", hide_buttons: true) %>');

$('#add-new-group').hide();

app/views/contacts/index.html.erb
<!-- content -->
<div class="col-md-3" id= "badges">
  <div class="card bg-white border-white border-0 card-custom badges">
    <div class="list-group list-group-flush">
      <%= render "contacts/badges" %>
    </div>
  </div>
</div>

<div class="col-md-9">
  <%= render "shared/contact_tools" %>
  <%= render "contacts" %>
</div>

app/views/contacts/index.js.erb
$('#contacts').html('<%= escape_javascript render(@contacts) %>');
$('#paginator').html('<%= escape_javascript(paginate(@contacts, remote: true)) %>');
$('#badges').html('<%= escape_javascript render("contacts/badges") %>');
<!-- $('#group_id').val('<%# params[:group_id] %>'); -->

app/views/contacts/new.html.erb
<div class="col-md-12">
  <div class="card bg-default card-custom border-white border-0 contact-card-container">
    <h5 class="card-header">
      Add Contact
    </h5>
  
    <%= render 'form' %>
  </div>
</div>

app/views/contacts/new.js.erb
$('#form-modal-title').html('Add New Contact')
$('#form-modal-body').html('<%= j render("contacts/form", hide_buttons: true) %>');

$('#add-new-group').hide();

app/views/dashboard/index.html.erb
<div class="col-md-8" style="margin: 0 auto">
  <div class="card bg-light rounded card-custom bg-white border-white border-0" style="padding: 3rem;">
    <div class="card-body">
      <h1 class="card-title">Hello
      <%= current_user.name.titleize %>!</h1>
      <p class="lead">From here you can manage your contacts as you like...</p>
      <%= link_to "Manage Your Contacts", contacts_path, class: "btn btn-lg btn-primary" %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="col-md-12">
  <div class="card bg-light rounded card-custom bg-white border-white border-0" style="padding: 3rem;">
    <div class="card-body">
      <h1 class="text-center card-title">Welcome to Contact Rails</h1>
      <h3 class="text-center text-muted card-title">Free Online Contact Manager</h3>
      <br>
      <p class="text-center text-monospace card-text">Organize your contacts freely and easily</p>
      <div class="row">
        <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg col" %>
        <%= link_to "Log In", new_user_session_path, class: "btn btn-outline-primary btn-lg col ml-3" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_flash_messages.html.erb
<% unless flash.empty? %>
  <script>
    <% flash.each do |type, message| %>
      <% type = type.to_s.gsub('alert', 'error').gsub('notice', 'info') %>
      toastr["<%= type %>"]("<%= message %>", "<%= type.upcase %>")
    <% end %>
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactManager</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta http-equiv="X-UA-Compatible" content="IE=7">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <%= render 'shared/navbar' %>

          <%= render 'layouts/flash_messages' %>

          <% if user_signed_in? %>
            <!-- content -->
            <div class="container container-contacts">
              <div class="row">
                <%= yield %>
              </div>
            </div>
          <% else %>
            <div class="container container-contacts">
              <div class="row">
                <div class="col-md-8" style="margin: 0 auto;">
                  <%= yield %>
                </div>
              </div>
            </div>
          <% end %>

        </div>
      </div>
    </div>
  </body>
</html>

app/views/shared/_contact_tools.html.erb
<ul class="nav navbar-light justify-content-end contact-tools" style="background-color: #e3f2fd;">
  <li class="nav-item search">
    <%= render 'shared/search' %>
  </li>
  <li class="nav-item">
    <%= link_to new_contact_path, class: "btn btn-outline-primary", data: {toggle: "modal", target: "#form-modal"}, remote: true do %>
      <i class="glyphicon glyphicon-plus"></i>
      Add Contact
    <% end %>
  </li>
</ul>

app/views/shared/_messages.html.erb
<% flash.each do |type, message| %>
  <%= content_tag :div, message, class: "alert alert-#{conversion_alert(type)}" %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top shadow">
  <div class="container">
    <%= link_to "Contact Rails", nav_link(current_user), class: "nav-link nav-title" %>
    <% if user_signed_in? %>
      <ul class="navbar-nav">
        <li class="nav-item <%= active?(dashboard_path) %>">
          <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= active?(contacts_path) %>">
          <%= link_to "All Contacts", contacts_path, class: "nav-link" %>
        </li>
      </ul>
    <% end %>

    <div class="navbar-nav ml-3">
      <% if user_signed_in? %>
        <div class="dropdown">
          <button class="btn btn-outline-light dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false">
            <%= current_user.name.titleize %>
          </button>
        
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <%= link_to "Profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item text-danger" %>
          </div>
        </div>
      <% else %>
        <%= link_to "Log In", new_user_session_path, class: "btn btn-outline-light" %>
        <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-light ml-3" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_search.html.erb
<%= form_tag(contacts_path, class: "form-inline my-lg-0", role: "search", method: :get) do %>
  <%= text_field_tag :term, params[:term], class: "form-control mr-sm-2", placeholder: "Search", autocomplete: "off", id: "term" %>
  <!-- <%# hidden_field_tag :group_id, params[:group_id] %> -->
  <button class="btn btn-primary" type="submit">Find</button>
 <% end %>